export type DataTableConfig = typeof dataTableConfig

export const dataTableConfig = {
    textOperators: [
        { label: 'contém', value: 'iLike' as const },
        { label: 'não contém', value: 'notILike' as const },
        { label: 'é', value: 'eq' as const },
        { label: 'não é', value: 'ne' as const },
        // { label: 'está vazio', value: 'isEmpty' as const },
        // { label: 'não está vazio', value: 'isNotEmpty' as const },
    ],
    numericOperators: [
        { label: 'é', value: 'eq' as const },
        { label: 'não é', value: 'ne' as const },
        { label: 'menor que', value: 'lt' as const },
        { label: 'menor ou igual a', value: 'lte' as const },
        { label: 'maior que', value: 'gt' as const },
        { label: 'maior ou igual a', value: 'gte' as const },
        { label: 'entre', value: 'isBetween' as const },
        { label: 'está vazio', value: 'isEmpty' as const },
        { label: 'não está vazio', value: 'isNotEmpty' as const },
    ],
    dateOperators: [
        { label: 'é', value: 'eq' as const },
        { label: 'não é', value: 'ne' as const },
        { label: 'antes de', value: 'lt' as const },
        { label: 'depois de', value: 'gt' as const },
        { label: 'no dia ou antes de', value: 'lte' as const },
        { label: 'no dia ou após', value: 'gte' as const },
        { label: 'entre', value: 'isBetween' as const },
        { label: 'relativo a hoje', value: 'isRelativeToToday' as const },
        { label: 'está vazio', value: 'isEmpty' as const },
        { label: 'não está vazio', value: 'isNotEmpty' as const },
    ],
    selectOperators: [
        { label: 'é', value: 'eq' as const },
        { label: 'não é', value: 'ne' as const },
        // { label: 'está vazio', value: 'isEmpty' as const },
        // { label: 'não está vazio', value: 'isNotEmpty' as const },
    ],
    multiSelectOperators: [
        { label: 'tem qualquer um de', value: 'inArray' as const },
        { label: 'não tem nenhum de', value: 'notInArray' as const },
        // { label: 'está vazio', value: 'isEmpty' as const },
        // { label: 'não está vazio', value: 'isNotEmpty' as const },
    ],
    booleanOperators: [
        { label: 'é', value: 'eq' as const },
        { label: 'não é', value: 'ne' as const },
    ],
    sortOrders: [
        { label: 'Ascendente', value: 'asc' as const },
        { label: 'Descendente', value: 'desc' as const },
    ],
    filterVariants: [
        'text',
        'number',
        'range',
        'date',
        'dateRange',
        'boolean',
        'select',
        'multiSelect',
    ] as const,
    operators: [
        'iLike',
        'notILike',
        'eq',
        'ne',
        'inArray',
        'notInArray',
        'isEmpty',
        'isNotEmpty',
        'lt',
        'lte',
        'gt',
        'gte',
        'isBetween',
        'isRelativeToToday',
    ] as const,
    joinOperators: ['and', 'or'] as const,
}
